#!/usr/bin/env php
<?php

$_ENV['HOME'] = getenv('HOME');
$_ENV['VAGRANT_DOTFILE_PATH'] = homestead_path().DIRECTORY_SEPARATOR.'.vagrant';

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

function homestead_path()
{
    if (isset($_SERVER['HOME'])) {
        return $_SERVER['HOME'].'/.sweet-home';
    } else {
        return $_SERVER['HOMEDRIVE'].$_SERVER['HOMEPATH'].DIRECTORY_SEPARATOR.'.sweet-home';
    }
}

$app = new Symfony\Component\Console\Application('Sweet Home', '0.1.3');

$app->add(new Sweethome\DestroyCommand);
$app->add(new Sweethome\EditCommand);
$app->add(new Sweethome\HaltCommand);
$app->add(new Sweethome\InitCommand);
$app->add(new Sweethome\ProvisionCommand);
$app->add(new Sweethome\ResumeCommand);
$app->add(new Sweethome\RunCommand);
$app->add(new Sweethome\UpCommand);
$app->add(new Sweethome\UpdateCommand);
$app->add(new Sweethome\SshCommand);
$app->add(new Sweethome\SshConfigCommand);
$app->add(new Sweethome\StatusCommand);
$app->add(new Sweethome\SuspendCommand);

$app->run();
